export const GAMES = {
  lol: {
    key: 'lol',
    name: 'League of Legends',
    nameKo: '리그 오브 레전드',
    color: '#C89B3C',
    emoji: '⚔️',
    ranks: ['Iron','Bronze','Silver','Gold','Platinum','Emerald','Diamond','Master','Grandmaster','Challenger'],
    isMultiplayer: true,
    communityOnly: false,
  },
  valorant: {
    key: 'valorant',
    name: 'Valorant',
    nameKo: '발로란트',
    color: '#FF4655',
    emoji: '🔫',
    ranks: ['Iron','Bronze','Silver','Gold','Platinum','Diamond','Ascendant','Immortal','Radiant'],
    isMultiplayer: true,
    communityOnly: false,
  },
  overwatch2: {
    key: 'overwatch2',
    name: 'Overwatch 2',
    nameKo: '오버워치 2',
    color: '#FA9C1E',
    emoji: '🦸',
    ranks: ['Bronze','Silver','Gold','Platinum','Diamond','Master','Grandmaster','Top 500'],
    isMultiplayer: true,
    communityOnly: false,
  },
  pubg: {
    key: 'pubg',
    name: 'PUBG: Battlegrounds',
    nameKo: '배틀그라운드',
    color: '#F5C518',
    emoji: '🐔',
    ranks: ['Bronze','Silver','Gold','Platinum','Diamond','Master'],
    isMultiplayer: true,
    communityOnly: false,
  },
  starcraft2: {
    key: 'starcraft2',
    name: 'StarCraft II',
    nameKo: '스타크래프트 II',
    color: '#1578DA',
    emoji: '🚀',
    ranks: ['Bronze','Silver','Gold','Platinum','Diamond','Master','Grandmaster'],
    isMultiplayer: true,
    communityOnly: false,
  },
  lostark: {
    key: 'lostark',
    name: 'Lost Ark',
    nameKo: '로스트아크',
    color: '#A259FF',
    emoji: '⚓',
    ranks: [] as string[],
    itemLevelBrackets: ['1000-1300','1300-1400','1400-1500','1500-1600','1600+'],
    isMultiplayer: true,
    communityOnly: false,
  },
  fifaonline4: {
    key: 'fifaonline4',
    name: 'FIFA Online 4',
    nameKo: '피파온라인 4',
    color: '#00D4AA',
    emoji: '⚽',
    ranks: ['Division 20-11','Division 10-6','Division 5-1','Elite Division'],
    isMultiplayer: true,
    communityOnly: false,
  },
  slaythespire2: {
    key: 'slaythespire2',
    name: 'Slay the Spire 2',
    nameKo: '슬레이 더 스파이어 2',
    color: '#8B5CF6',
    emoji: '🃏',
    ranks: [] as string[],
    isMultiplayer: false,
    communityOnly: true,
  },
} as const;

export type GameKey = keyof typeof GAMES;

export const PLAY_STYLES = [
  { key: 'competitive', label: 'Competitive', labelKo: '경쟁적', emoji: '🏆' },
  { key: 'chill', label: 'Chill', labelKo: '여유롭게', emoji: '😌' },
  { key: 'voice_ok', label: 'Voice OK', labelKo: '음성 가능', emoji: '🎤' },
  { key: 'no_mic', label: 'No Mic', labelKo: '마이크 없음', emoji: '🔇' },
  { key: 'night_owl', label: 'Night Owl', labelKo: '밤샘', emoji: '🌙' },
  { key: 'early_bird', label: 'Early Bird', labelKo: '아침형', emoji: '🌅' },
  { key: 'beginner_friendly', label: 'Beginner Friendly', labelKo: '초보환영', emoji: '🌱' },
  { key: 'carry_me', label: 'Carry Me', labelKo: '캐리해줘', emoji: '🙏' },
  { key: 'teaching', label: 'Happy to Teach', labelKo: '가르쳐 줄게', emoji: '📚' },
  { key: 'tryhard', label: 'Tryhard', labelKo: '열심히', emoji: '💪' },
] as const;

export type PlayStyleKey = typeof PLAY_STYLES[number]['key'];
